# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: 5.0.x
    displayName: 'Install .NET 5'
    
- script: dotnet restore
  condition: succeeded()
  displayName: 'Restore Solution'

- script: dotnet test
  condition: succeeded()
  displayName: 'Test Solution'

- script: dotnet build
  condition: succeeded()
  displayName: 'Pre-build'

- script: dotnet publish --configuration $(buildConfiguration) --runtime linux-x64 --output $(Build.ArtifactStagingDirectory) --verbosity n
  condition: succeeded()
  displayName: 'Publish Solution'

- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Publish Build Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: uploadr